services:
  icmr:
    image: ${CONTAINER_REGISTRY:+$CONTAINER_REGISTRY/}preprocess-icmr:latest
    volumes:
      - $ICMR_INPUT_PATH:/mnt/depa_ccr_poc/data
      - $ICMR_OUTPUT_PATH:/mnt/output/icmr
    command: ["python3", "ccr_depa_covid_poc_dp_data_prep_icmr.py"]
  index:
    image: ${CONTAINER_REGISTRY:+$CONTAINER_REGISTRY/}preprocess-index:latest
    volumes:
      - $INDEX_INPUT_PATH:/mnt/depa_ccr_poc/data
      - $INDEX_OUTPUT_PATH:/mnt/output/index
    command: ["python3", "ccr_depa_covid_poc_dp_data_prep_index.py"]
  cowin:
    image: ${CONTAINER_REGISTRY:+$CONTAINER_REGISTRY/}preprocess-cowin:latest
    volumes:
      - $COWIN_INPUT_PATH:/mnt/depa_ccr_poc/data
      - $COWIN_OUTPUT_PATH:/mnt/output/cowin
    command: ["python3", "ccr_depa_covid_poc_dp_data_prep_cowin.py"]
