services:
  mnist_1:
    image: ${CONTAINER_REGISTRY:+$CONTAINER_REGISTRY/}preprocess-mnist_1:latest
    volumes:
      - $MNIST_1_INPUT_PATH:/mnt/depa_ccr_poc/data
      - $MNIST_1_OUTPUT_PATH:/mnt/output/mnist_1
    command: ["python3", "ccr_depa_covid_poc_dp_data_prep_mnist_1.py"]
  mnist_2:
    image: ${CONTAINER_REGISTRY:+$CONTAINER_REGISTRY/}preprocess-mnist_2:latest
    volumes:
      - $MNIST_2_INPUT_PATH:/mnt/depa_ccr_poc/data
      - $MNIST_2_OUTPUT_PATH:/mnt/output/mnist_2
    command: ["python3", "ccr_depa_covid_poc_dp_data_prep_mnist_2.py"]
  mnist_3:
    image: ${CONTAINER_REGISTRY:+$CONTAINER_REGISTRY/}preprocess-mnist_3:latest
    volumes:
      - $MNIST_3_INPUT_PATH:/mnt/depa_ccr_poc/data
      - $MNIST_3_OUTPUT_PATH:/mnt/output/mnist_3
    command: ["python3", "ccr_depa_covid_poc_dp_data_prep_mnist_3.py"]
