services:
  train:
    image: ${CONTAINER_REGISTRY:+$CONTAINER_REGISTRY/}depa-training:latest
    volumes:
      - $MNIST_INPUT_PATH:/mnt/remote/mnist
      - $MODEL_INPUT_PATH:/mnt/remote/model
      - $MODEL_OUTPUT_PATH:/mnt/remote/output
      - $CONFIGURATION_PATH:/mnt/remote/config
    command: ["/bin/bash", "run.sh"]
 